### ISSUE TITLE
Input data description?

### ISSUE THREAD

**Issue by liz-is** [pcahan1/epoch#4]
Hi,
I'm interested in using epoch on data processed in R with Seurat. As I'll be extracting the data from the Seurat object rather than a loom file, I was wondering if you could provide a brief definition of the data that should be in the objects you save in variables `expDat` and `sampTab`? 

From a quick look at the code I think `sampTab` should be cell metadata and `expDat` should be a genes x cells matrix of (normalised & log-transformed) expression data, is that correct? It would be really helpful if this info was included in the example analysis to make it easier to follow.

Thanks!

**Comment by esu12** [comment]
Hi,

Yes that's exactly correct!
Thanks for pointing this out, we've updated the documentation to include these descriptions.

**Comment by liz-is** [comment]
Great, thank you!
